version: '3'
services:
  moodle:
    image: jorarmarfin/moodle:4.0.4
    container_name: srv-moodle-apache
    volumes:
      - ./backup:/backup
    ports:
      - 9001:80
    restart: always
    networks:
      - net-moodle
  db:
    container_name: srv-moodle-mysql
    image: jorarmarfin/mysql:5.7-moodle-4.0.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=examfactory
    restart: always
    networks:
      - net-moodle
  adminer:
    container_name: srv-moodle-adminer
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always
    networks:
      - net-moodle
networks:
  net-moodle:
